set shell := ["pwsh.exe", "-NoLogo", "-Command"]

# Default target
_default:
    just --list

# Node / extension lifecycle
compile:
    npm run compile

lint:
    npm run lint

typecheck:
    npm run check-types

watch:
    npm run watch

server:
    npm run server

test:
    npm run test

# WASM lifecycle
wasm-build:
    npm run build:wasm

wasm-check:
    cargo check --manifest-path wasm/frikfrak_wasm/Cargo.toml --target wasm32-unknown-unknown

wasm-release:
    cargo build --manifest-path wasm/frikfrak_wasm/Cargo.toml --target wasm32-unknown-unknown --release

# Combined pipelines
verify:
    npm run check-types
    npm run lint
    npm run compile

all-build:
    npm run compile
    npm run build:wasm

# Plan and hook helpers
hooks-log:
    if (Test-Path logs/hooks.log) { Get-Content logs/hooks.log -Tail 80 } else { Write-Output "logs/hooks.log not found" }

plan-open:
    if (Test-Path plan/progress.md) { Get-Content plan/progress.md -TotalCount 120 }

# Python helper (optional)
py-venv:
    if (!(Test-Path .venv)) { py -m venv .venv }
    Write-Output ".venv ready"

# Clean local build outputs commonly regenerated by this repo
clean:
    if (Test-Path dist) { Remove-Item -Recurse -Force dist }
    if (Test-Path out) { Remove-Item -Recurse -Force out }
